package product

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// E2EGeneratorOptions configures skeleton E2E test generation from a flow YAML.
type E2EGeneratorOptions struct {
	Product string
	FlowID  string
	Runner  string // playwright (default) or cypress
	DryRun  bool
}

// E2EGeneratorResult summarizes a generation run.
type E2EGeneratorResult struct {
	FlowID   string
	Path     string
	Runner   string
	StepCount int
}

// GenerateE2ETest writes a skeleton Playwright or Cypress test from a product flow.
func (s *Service) GenerateE2ETest(opts E2EGeneratorOptions) (E2EGeneratorResult, error) {
	product := Slug(opts.Product)
	flowID := strings.TrimSpace(opts.FlowID)
	if flowID == "" {
		return E2EGeneratorResult{}, fmt.Errorf("flow id is required")
	}
	runner := strings.ToLower(strings.TrimSpace(opts.Runner))
	if runner == "" {
		runner = "playwright"
	}
	if runner != "playwright" && runner != "cypress" {
		return E2EGeneratorResult{}, fmt.Errorf("runner must be playwright or cypress")
	}

	flow, err := s.loadFlow(product, flowID)
	if err != nil {
		return E2EGeneratorResult{}, err
	}
	if err := ValidateFlow(flow); err != nil {
		return E2EGeneratorResult{}, err
	}

	var relPath string
	var body []byte
	switch runner {
	case "cypress":
		relPath = filepath.Join("tests", "e2e", flowID+".cy.ts")
		body = []byte(renderCypressE2E(flow))
	default:
		relPath = filepath.Join("tests", "e2e", flowID+".spec.ts")
		body = []byte(renderPlaywrightE2E(flow))
	}

	result := E2EGeneratorResult{
		FlowID:    flow.ID,
		Path:      filepath.Join(s.repo.productRoot(product), relPath),
		Runner:    runner,
		StepCount: len(flow.Steps),
	}
	if opts.DryRun {
		return result, nil
	}
	if err := s.repo.WriteProductFile(product, relPath, body); err != nil {
		return E2EGeneratorResult{}, err
	}
	return result, nil
}

func (s *Service) loadFlow(product, flowID string) (Flow, error) {
	path := filepath.Join(s.repo.productRoot(product), "flows", flowID+".flow.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return Flow{}, fmt.Errorf("flow %q not found under .asagiri/products/%s/flows/: %w", flowID, product, err)
	}
	return ParseFlowYAML(data)
}

func renderPlaywrightE2E(flow Flow) string {
	var b strings.Builder
	b.WriteString("import { test, expect } from '@playwright/test';\n\n")
	b.WriteString("// Generated by asa flows e2e — skeleton only; wire selectors and baseURL.\n")
	_, _ = fmt.Fprintf(&b, "test.describe(%q, () => {\n", flow.Title)
	_, _ = fmt.Fprintf(&b, "  test(%q, async ({ page }) => {\n", "completes "+flow.ID)
	_, _ = fmt.Fprintf(&b, "    // entry_screen: %s | outcome: %s\n", flow.Entry, flow.Outcome)
	for _, step := range flow.Steps {
		_, _ = fmt.Fprintf(&b, "    // %s: screen=%s action=%s", step.ID, step.Screen, step.Action)
		if step.Next != "" {
			_, _ = fmt.Fprintf(&b, " next=%s", step.Next)
		}
		if step.ContractRef != "" {
			_, _ = fmt.Fprintf(&b, " contract=%s", step.ContractRef)
		}
		b.WriteString("\n")
		_, _ = fmt.Fprintf(&b, "    // TODO: await page.getByTestId(%q).click();\n", step.Action)
	}
	b.WriteString("    expect(true).toBe(true); // replace with flow assertions\n")
	b.WriteString("  });\n")
	b.WriteString("});\n")
	return b.String()
}

func renderCypressE2E(flow Flow) string {
	var b strings.Builder
	b.WriteString("// Generated by asa flows e2e — skeleton only; wire selectors and baseUrl.\n")
	_, _ = fmt.Fprintf(&b, "describe(%q, () => {\n", flow.Title)
	_, _ = fmt.Fprintf(&b, "  it(%q, () => {\n", "completes "+flow.ID)
	_, _ = fmt.Fprintf(&b, "    // entry_screen: %s | outcome: %s\n", flow.Entry, flow.Outcome)
	for _, step := range flow.Steps {
		_, _ = fmt.Fprintf(&b, "    // %s: screen=%s action=%s", step.ID, step.Screen, step.Action)
		if step.Next != "" {
			_, _ = fmt.Fprintf(&b, " next=%s", step.Next)
		}
		if step.ContractRef != "" {
			_, _ = fmt.Fprintf(&b, " contract=%s", step.ContractRef)
		}
		b.WriteString("\n")
		_, _ = fmt.Fprintf(&b, "    // TODO: cy.get('[data-testid=%q]').click();\n", step.Action)
	}
	b.WriteString("    expect(true).to.eq(true); // replace with flow assertions\n")
	b.WriteString("  });\n")
	b.WriteString("});\n")
	return b.String()
}
